### ISSUE TITLE
Unable to start apihandler. Cannot find start.sh

### ISSUE THREAD

**Issue by utmishra** [octoai/apihandler#7]
Hi,

I am not able to run Octo.ai setup. As per the README.md file, I should be running ./start.sh from the project directory. I am not able to find the same under apihandler folder or Octo-core folder.

Please guide where should I look for the script ? I also noticed tha Manual Setup was edited recently. Are the steps not thoroughly tested yet ? 

Thanks!

**Comment by pranny** [comment]
This file was removed in favour of docker setup. The way to start the server is `bundle exec unicorn -c config/unicorn.rb --daemonize`. The steps are verified to be working. The readme needs to be updated although. I will do that right away.

**Comment by utmishra** [comment]
Thanks for the update. 

Getting following error on attempting to start server with `bundle exec unicorn -c config/unicorn.rb --daemonize`.

`master failed to start, check stderr log for details`

My setup is still not complete (apihandler and tasks/db:migrate is done though). Could this be the reason ?

**Comment by pranny** [comment]
- Can you paste your `unicorn.stderr.log` output? It should be in `shared/log/` directory
- Try without the `--daemonize` option to see what happens

**Comment by utmishra** [comment]
My bad! 

I ran the command twice, and I was checking whether its running or not by `ps aux | grep apihandler`. I should've tried `ps aux | grep unicorn` or something like that.

Thanks for the update. I am still going through the setup and posting more known issues on the octoai repo.

**Comment by pranny** [comment]
Sure. Happy to help :)

**Comment by pranny** [comment]
I should update the log file details on README as well

**Comment by pranny** [comment]
Done.
